import { Router } from "express";
import auth from "./modules/authentication/authentication.routes.js";
import account from "./modules/authentication/account.routes.js";
import registry from "./modules/account-registry/account-registry.routes.js";
import rfid from "./modules/rfid/rfid.routes.js";
import store from "./modules/store/store.routes.js";
import requests from "./modules/request/request.routes.js";
import notifications from "./modules/notification/notification.routes.js";
import gps from "./modules/gps/gps.routes.js";
import reports from "./modules/report/report.routes.js";
import devices from "./modules/gps/device-management.js";
const routes = Router();
routes.use("/auth", auth);
routes.use("/account", account);
routes.use("/account-registry", registry);
routes.use("/rfid", rfid);
routes.use("/store", store);
routes.use("/request", requests);
routes.use("/notifications", notifications);
routes.use("/gps", gps);
routes.use("/devices", devices);
routes.use("/reports", reports);
export default routes;
